#include "Managers.h"
StateManager* g_pStateManager;
ResourceManager* g_pResourceManager;
GraphicsManager* g_pGraphicsManager;
FontManager* g_pFontManager;
InputManager* g_pInputManager;
PhysicsManager* g_pPhysicsManager;
NetworkManager* g_pNetworkManager;
AudioManager* g_pAudioManager;
StatisticsManager* g_pStatisticsManager;
SceneManager* g_pSceneManager;
WindowManager* g_pWindowManager;